import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";

export function runGenerate(configPath: string, outputPath: string): void {
  const resolvedConfig = resolve(configPath);
  if (!existsSync(resolvedConfig)) {
    console.error(`Config file not found: ${configPath}`);
    process.exit(1);
  }

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require(resolvedConfig);
  const config = mod.default ?? mod;

  if (typeof config?.toObject !== "function") {
    console.error("Config file must export a defineConfig() result as default export");
    process.exit(1);
  }

  // defineConfig 내부 스키마 정보를 직접 접근하기 위해 __schema 노출 필요
  // 현재는 toObject() 결과와 기본 패턴으로 .env.example 생성
  const obj = config.toObject() as Record<string, unknown>;
  const lines: string[] = ["# Auto-generated by envault", ""];

  for (const [key, value] of Object.entries(obj)) {
    const displayValue = value === undefined ? "" : String(value);
    lines.push(`${key}=${displayValue}`);
  }

  const output = lines.join("\n") + "\n";
  writeFileSync(resolve(outputPath), output, "utf-8");
  console.log(`Generated ${outputPath} with ${Object.keys(obj).length} variable(s)`);
}
